### ISSUE TITLE
Support for Umlaut

### ISSUE THREAD

**Issue by Armiiin** [giovannicoppola/alfred-phoneticSpelling#1]
So even if you use a custom spelling dictionary the workflow seems to not be able to handle letters with umlaut and renders it incorrectly. You may see an example below.

<img width="744" alt="image" src="https://github.com/giovannicoppola/alfred-phoneticSpelling/assets/56965381/8a27aca0-8aa1-4ac4-a609-d7fac38be5cf">

Would be great if it could handle letters like Ä Å Ö correctly. 
Also a suggestion to add a Swedish dictionary. It is available here https://sv.wikipedia.org/wiki/Bokstavering

**Comment by giovannicoppola** [comment]
@Armiiin both are fixed in the latest release. thanks for your words of appreciation!

**Comment by Armiiin** [comment]
Great job, thank you!
